{{- if .Values.service.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "script-server.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "script-server.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ template "script-server.chart" . }}
  {{- with .Values.service.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
  {{- with .Values.service.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ template "script-server.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end -}}